allow upgrade to pass when upgrading between rcs (#11351)
# Description

Fixes error similar to below, where we are upgrading Radius from one rc
version to next.

https://github.com/radius-project/radius/actions/runs/22571565116/job/65380431400

Version mismatch detected. Attempting upgrade from 0.55.0-rc4 to
0.55.0-rc5...
Current Radius version: 0.55.0-rc4
Target Radius version: 0.55.0-rc5
Running pre-flight checks...
  Running Kubernetes Connectivity...
    ✓ Connected (version: v1.34.2) with sufficient permissions
  Running Helm Connectivity...
✓ Helm successfully connected to cluster and found Radius release
(version: 0.55.0-rc4), Contour installed (version: 1.32.0)
  Running Radius Installation...
✓ Radius is installed (version: 0.55.0-rc4), Contour is installed
(version: 1.32.0)
  Running Version Compatibility...
Error: ERROR] Only incremental version upgrades are supported. Expected
next version: 0.56.0
Error: preflight checks failed: pre-flight check 'Version Compatibility'
failed: Only incremental version upgrades are supported. Expected next
version: 0.56.0

## Type of change

- This pull request is a minor refactor, code cleanup, test improvement,
or other maintenance task and doesn't change the functionality of Radius
(issue link optional).

## Contributor checklist
Please verify that the PR meets the following requirements, where
applicable:

<!--
This checklist uses "TaskRadio" comments to make certain options
mutually exclusive.
See:
https://github.com/mheap/require-checklist-action?tab=readme-ov-file#radio-groups
For details on how this works and why it's required.
-->

- An overview of proposed schema changes is included in a linked GitHub
issue.
    - [ ] Yes <!-- TaskRadio schema -->
    - [x] Not applicable <!-- TaskRadio schema -->
- A design document PR is created in the [design-notes
repository](https://github.com/radius-project/design-notes/), if new
APIs are being introduced.
    - [ ] Yes <!-- TaskRadio design-pr -->
    - [x] Not applicable <!-- TaskRadio design-pr -->
- The design document has been reviewed and approved by Radius
maintainers/approvers.
    - [ ] Yes <!-- TaskRadio design-review -->
    - [x] Not applicable <!-- TaskRadio design-review -->
- A PR for the [samples
repository](https://github.com/radius-project/samples) is created, if
existing samples are affected by the changes in this PR.
    - [ ] Yes <!-- TaskRadio samples-pr -->
    - [x] Not applicable <!-- TaskRadio samples-pr -->
- A PR for the [documentation
repository](https://github.com/radius-project/docs) is created, if the
changes in this PR affect the documentation or any user facing updates
are made.
    - [ ] Yes <!-- TaskRadio docs-pr -->
    - [x] Not applicable <!-- TaskRadio docs-pr -->
- A PR for the [recipes
repository](https://github.com/radius-project/recipes) is created, if
existing recipes are affected by the changes in this PR.
    - [ ] Yes <!-- TaskRadio recipes-pr -->
    - [x] Not applicable <!-- TaskRadio recipes-pr -->

---------

Signed-off-by: nithyatsu <nithyasu@microsoft.com>
Signed-off-by: Will Tsai <28876888+willtsai@users.noreply.github.com>